project:
  type: website
  title: "decrochage"

editor: visual

website:
  code-links:
    - text: Github
      icon: github
      href: https://github.com/xtimbeau/decrochage
    - text: Données OCDE
      icon: file-code
      href: oecd.r
    - text: Données WID
      icon: file-code
      href: wid.r
    - text: English version
      icon: file-code
      href: index.en.html


format:
  ofce-html:
    number-depth: 4
    number-sections: TRUE
    toc-depth: 4
    image-lazy-loading: true
    toc-title: Sur cette page
